### ISSUE TITLE
Mac OS: Dynamic library install names are not set properly (aka. Hello, adam!)

### ISSUE THREAD

**Issue by IngwiePhoenix** [ultralight-ux/ultralight#86]
**Summarize the Issue**
After building, when trying to execute the Browser example, DYLD reports a missing library and presents me with a path that clearly does not exist on my system. This usually means that installnames are not set properly.

**Steps to Reproduce**
```
Ingwie@Ingwies-MBP.fritz.box ~/W/G/u/out $ ./samples/Browser/Browser.app/Contents/MacOS/Browser 
dyld: Library not loaded: /Users/adam/dev/ultralight/deps/AppCore/build/libAppCore.dylib
  Referenced from: /Users/Ingwie/Work/Git/ultralight/out/./samples/Browser/Browser.app/Contents/MacOS/Browser
  Reason: image not found
fish: './samples/Browser/Browser.app/C…' terminated by signal SIGABRT (Abort)
```

**Platform Info:**
 - OS:
```
ProductName:	Mac OS X
ProductVersion:	10.14.3
BuildVersion:	18D109
```
 - SDK Version:
```
$ git rev-parse HEAD
91298b7c0670f253a9a587e69cee1edb2cb920c1
```

**Comment by adamjs** [comment]
Hah yes, caught this a little earlier-- fixed in [this commit](https://github.com/ultralight-ux/ultralight/commit/9ea26b3bc2566662a4a01c6220d3fabfdc0a1dbf). I've updated the bins on the release and website with v2.

**Comment by IngwiePhoenix** [comment]
I did a `git pull` and re-ran `make`, but I get the error still. I will try to clean the build directory and retry.

**Comment by IngwiePhoenix** [comment]
Yeah, that worked. Weird that re-running Make does not pick up the changed library... Anyway, thanks for that!
